import TelegramBot from 'node-telegram-bot-api';
import { config, type GuestBot } from '../config.js';
import { runAgent } from '../agent/orchestrator.js';
import { transcribeFromUrl, transcriptionEnabled } from './transcribe.js';
import {
  githubEnabled,
  githubCredsValid,
  setPendingHtml,
  deployHtml,
} from '../deploy/github.js';
import { extractPdfText } from './parsePdf.js';
import { drainMedia } from '../generate/queue.js';

/**
 * Telegram transport. Long-polling for local dev — no public URL needed.
 *
 * This one app runs MULTIPLE bots off a single process:
 *  - The KEEPER bot (Philip): the full proactive agent with memory + touchpoints.
 *  - Zero or more GUEST bots: deploy-only. They can publish an .html file to
 *    their OWN GitHub Pages and nothing else — no memory, no agent, no access
 *    to Philip's life. Configured via GUEST_BOTS (see config.ts).
 */
const keeperBot = new TelegramBot(config.telegramBotToken, { polling: true });
const OWNER = String(config.telegramOwnerChatId);

/** Send a message to the owner (Philip). Used by reactive + proactive paths. */
export async function sendToOwner(text: string): Promise<void> {
  await keeperBot.sendMessage(OWNER, text);
}

/** Drain the media queue (images/PDFs generated by the agent) and send each to the owner. */
export async function flushMediaToOwner(): Promise<void> {
  for (const item of drainMedia()) {
    try {
      if (item.kind === 'photo') {
        await keeperBot.sendPhoto(OWNER, item.buffer, { caption: item.caption });
      } else {
        await keeperBot.sendDocument(OWNER, item.buffer, { caption: item.caption }, { filename: item.filename, contentType: 'application/pdf' });
      }
    } catch (err) {
      console.error('[telegram] failed to send media:', err);
    }
  }
}

/**
 * Resolve an inbound message to plain text. Text messages pass through;
 * voice notes / audio get transcribed via Groq Whisper first.
 * Returns null if there's nothing actionable to send to the agent.
 */
async function extractText(msg: TelegramBot.Message): Promise<string | null> {
  if (msg.text && msg.text.trim()) return msg.text.trim();

  const media = msg.voice ?? msg.audio;
  if (media) {
    if (!transcriptionEnabled()) {
      await sendToOwner(
        "i can't listen to voice notes yet — drop a GROQ_API_KEY in my config and i'll have ears. for now, text me?"
      );
      return null;
    }
    try {
      await keeperBot.sendChatAction(OWNER, 'typing');
      const fileUrl = await keeperBot.getFileLink(media.file_id);
      const transcript = await transcribeFromUrl(fileUrl);
      console.log(`[telegram] transcribed voice note (${transcript.length} chars).`);
      return transcript;
    } catch (err) {
      console.error('[telegram] transcription failed:', err);
      await sendToOwner("i couldn't make out that voice note — mind sending it again or texting it?");
      return null;
    }
  }

  return null; // stickers, photos, etc. — nothing to act on
}

/** Download a Telegram document and return its text contents. */
async function downloadText(bot: TelegramBot, fileId: string): Promise<string> {
  const fileUrl = await bot.getFileLink(fileId);
  const res = await fetch(fileUrl);
  return res.text();
}

/** The KEEPER bot — Philip only, full agent. */
function startKeeperBot(): void {
  keeperBot.on('message', async (msg) => {
    const chatId = String(msg.chat.id);
    // Single-user agent: ignore anyone who isn't the owner.
    if (chatId !== OWNER) {
      console.warn(`[telegram] ignoring message from non-owner chat ${chatId}`);
      return;
    }

    const text = await extractText(msg);
    if (!text) return;

    try {
      await keeperBot.sendChatAction(OWNER, 'typing');
      const result = await runAgent({ kind: 'inbound', text });
      if (result.message) await sendToOwner(result.message);
      await flushMediaToOwner();
    } catch (err) {
      console.error('[telegram] runAgent failed:', err);
      await sendToOwner('(something glitched on my end — try me again in a sec)');
    }
  });

  // Document uploads: .html → deploy to GitHub Pages; .pdf → extract + agent.
  keeperBot.on('document', async (msg) => {
    const chatId = String(msg.chat.id);
    if (chatId !== OWNER) return;

    const doc = msg.document;
    if (!doc) return;
    const name = doc.file_name ?? '';
    const ext = name.toLowerCase().match(/\.\w+$/)?.[0] ?? '';

    if (ext === '.html') {
      if (!githubEnabled()) {
        await sendToOwner("i can't deploy sites yet — i need GITHUB_TOKEN and GITHUB_USERNAME in my config.");
        return;
      }
      try {
        await keeperBot.sendChatAction(OWNER, 'typing');
        const html = await downloadText(keeperBot, doc.file_id);
        setPendingHtml({
          filename: name,
          contentBase64: Buffer.from(html).toString('base64'),
          sizeBytes: html.length,
        });
        const result = await runAgent({
          kind: 'inbound',
          text: `I just sent you an HTML file named "${name}" (${(html.length / 1e6).toFixed(2)} MB). Please deploy it to GitHub Pages and give me the live link.`,
        });
        if (result.message) await sendToOwner(result.message);
        await flushMediaToOwner();
      } catch (err) {
        console.error('[telegram] html deploy failed:', err);
        await sendToOwner(`(couldn't deploy that file — ${(err as Error).message})`);
      }
      return;
    }

    if (ext === '.pdf') {
      try {
        await keeperBot.sendChatAction(OWNER, 'typing');
        const fileUrl = await keeperBot.getFileLink(doc.file_id);
        const pdf = await extractPdfText(fileUrl);
        const truncNote = pdf.truncated
          ? `\n\n(note: pdf was long — only the first ~24k characters are included above)`
          : '';
        const result = await runAgent({
          kind: 'inbound',
          text:
            `I sent you a PDF named "${name}" (${pdf.pages} page${pdf.pages === 1 ? '' : 's'}). Here's its text content:\n\n` +
            pdf.text +
            truncNote,
        });
        if (result.message) await sendToOwner(result.message);
        await flushMediaToOwner();
      } catch (err) {
        console.error('[telegram] pdf parse failed:', err);
        await sendToOwner(`(couldn't read that PDF — ${(err as Error).message})`);
      }
      return;
    }

    // Any other file type — nothing to act on silently.
  });

  keeperBot.on('polling_error', (err) => {
    console.error('[telegram] polling error:', err.message);
    if ((err as NodeJS.ErrnoException).code === 'EFATAL') {
      console.error('[telegram] fatal network error — restarting polling in 20s...');
      keeperBot.stopPolling()
        .then(() => new Promise<void>((r) => setTimeout(r, 20_000)))
        .then(() => keeperBot.startPolling())
        .catch((e) => { console.error('[telegram] polling restart failed, exiting:', e); process.exit(1); });
    }
  });
  console.log('[telegram] keeper bot listening (long-polling).');
}

/**
 * A GUEST deploy-only bot. No agent, no memory — send an .html file, get back a
 * GitHub Pages link on the guest's own account. Optionally locked to one chat.
 */
function startGuestBot(g: GuestBot): void {
  const bot = new TelegramBot(g.telegramBotToken, { polling: true });
  const enabled = githubCredsValid(g.github);
  const allowed = (chatId: string) => !g.chatId || chatId === g.chatId;
  const tag = `telegram:${g.name}`;

  bot.on('document', async (msg) => {
    const chatId = String(msg.chat.id);
    if (!allowed(chatId)) {
      console.warn(`[${tag}] ignoring document from chat ${chatId}`);
      return;
    }

    const doc = msg.document;
    if (!doc) return;
    const name = doc.file_name ?? '';
    if (!name.toLowerCase().endsWith('.html')) {
      await bot.sendMessage(chatId, "send me an .html file and i'll publish it to your github pages.");
      return;
    }
    if (!enabled) {
      await bot.sendMessage(chatId, "this bot isn't set up to deploy yet — its github access is missing.");
      return;
    }

    try {
      await bot.sendChatAction(chatId, 'typing');
      const html = await downloadText(bot, doc.file_id);
      const res = await deployHtml(g.github, {
        filename: name,
        contentBase64: Buffer.from(html).toString('base64'),
        sizeBytes: html.length,
      });
      if (res.ok) {
        await bot.sendMessage(chatId, `done ✅ your site is live in ~30–60s:\n${res.url}`);
      } else {
        await bot.sendMessage(chatId, `couldn't deploy that — ${res.error}`);
      }
    } catch (err) {
      console.error(`[${tag}] document handler failed:`, err);
      await bot.sendMessage(chatId, `couldn't deploy that — ${(err as Error).message}`);
    }
  });

  bot.on('message', async (msg) => {
    if (msg.document) return; // handled above
    const chatId = String(msg.chat.id);
    if (!allowed(chatId)) return;
    await bot.sendMessage(
      chatId,
      `hey — send me an .html file and i'll publish it to your github pages and send you the link. that's all i do here.`
    );
  });

  bot.on('polling_error', (err) => {
    console.error(`[${tag}] polling error:`, err.message);
    if ((err as NodeJS.ErrnoException).code === 'EFATAL') {
      console.error(`[${tag}] fatal network error — restarting polling in 20s...`);
      bot.stopPolling()
        .then(() => new Promise<void>((r) => setTimeout(r, 20_000)))
        .then(() => bot.startPolling())
        .catch((e) => { console.error(`[${tag}] polling restart failed, exiting:`, e); process.exit(1); });
    }
  });
  console.log(
    `[telegram] guest deploy bot "${g.name}" listening${g.chatId ? ` (locked to chat ${g.chatId})` : ''}` +
      `${enabled ? '' : ' — WARNING: github creds missing, deploys disabled'}.`
  );
}

export function startTelegram(): void {
  startKeeperBot();
  for (const g of config.guestBots) startGuestBot(g);
  if (config.guestBots.length > 0) {
    console.log(`[telegram] ${config.guestBots.length} guest bot(s) started.`);
  }
}
