import TelegramBot from 'node-telegram-bot-api';
import { config, type GuestBot } from '../config.js';
import { runAgent } from '../agent/orchestrator.js';
import { localMidnightUtc, monthStartUtc } from '../agent/recurrence.js';
import { digests, goals, observations, touchpoints, journal } from '../db/repositories.js';
import { googleEnabled } from '../integrations/google.js';
import { imageGenEnabled } from '../generate/image.js';
import { transcribeFromUrl, transcriptionEnabled } from './transcribe.js';
import {
  githubEnabled,
  githubCredsValid,
  setPendingHtml,
  deployHtml,
} from '../deploy/github.js';
import { extractPdfText, extractPdfTextFromBuffer } from './parsePdf.js';
import { drainMedia } from '../generate/queue.js';

/**
 * Telegram transport. Long-polling for local dev — no public URL needed.
 *
 * This one app runs MULTIPLE bots off a single process:
 *  - The KEEPER bot (Philip): the full proactive agent with memory + touchpoints.
 *  - Zero or more GUEST bots: deploy-only. They can publish an .html file to
 *    their OWN GitHub Pages and nothing else — no memory, no agent, no access
 *    to Philip's life. Configured via GUEST_BOTS (see config.ts).
 */
const keeperBot = new TelegramBot(config.telegramBotToken, { polling: true });
const OWNER = String(config.telegramOwnerChatId);
const BOOTED_AT = Date.now();

const TG_LIMIT = 4096; // Telegram's hard per-message cap — exceeding it throws.

const sleep = (ms: number) => new Promise<void>((r) => setTimeout(r, ms));

/** Split a too-long message at a newline/space near the limit, never mid-word. */
function hardSplit(s: string): string[] {
  const out: string[] = [];
  let rest = s;
  while (rest.length > TG_LIMIT) {
    let cut = rest.lastIndexOf('\n', TG_LIMIT);
    if (cut < TG_LIMIT / 2) cut = rest.lastIndexOf(' ', TG_LIMIT);
    if (cut < TG_LIMIT / 2) cut = TG_LIMIT;
    out.push(rest.slice(0, cut).trimEnd());
    rest = rest.slice(cut).trimStart();
  }
  if (rest) out.push(rest);
  return out;
}

/**
 * Turn one agent reply into Telegram bubbles. Two or three short paragraphs
 * arrive as separate messages — the rhythm of a person texting, not an app
 * dumping a wall. Longer/structured replies stay as one message (then get
 * hard-split only if they'd blow Telegram's 4096-char cap).
 */
function toBubbles(text: string): string[] {
  const trimmed = text.trim();
  if (!trimmed) return [];
  const paras = trimmed.split(/\n\s*\n/).map((p) => p.trim()).filter(Boolean);
  const bubbles = paras.length >= 2 && paras.length <= 3 ? paras : [trimmed];
  return bubbles.flatMap(hardSplit);
}

/** Send a message to the owner (Philip). Used by reactive + proactive paths. */
export async function sendToOwner(text: string): Promise<void> {
  const bubbles = toBubbles(text);
  for (let i = 0; i < bubbles.length; i++) {
    if (i > 0) {
      await keeperBot.sendChatAction(OWNER, 'typing').catch(() => {});
      await sleep(Math.min(400 + (bubbles[i]?.length ?? 0) * 8, 1800));
    }
    await keeperBot.sendMessage(OWNER, bubbles[i]!);
  }
}

/**
 * Keep the "typing…" indicator alive for the whole agent run. A single
 * sendChatAction only lasts ~5s; a multi-tool turn can take 30s+ and going
 * quiet mid-thought reads as dead.
 */
async function withTyping<T>(fn: () => Promise<T>): Promise<T> {
  await keeperBot.sendChatAction(OWNER, 'typing').catch(() => {});
  const beat = setInterval(() => {
    void keeperBot.sendChatAction(OWNER, 'typing').catch(() => {});
  }, 4500);
  try {
    return await fn();
  } finally {
    clearInterval(beat);
  }
}

/** Drain the media queue (images/PDFs generated by the agent) and send each to the owner. */
export async function flushMediaToOwner(): Promise<void> {
  for (const item of drainMedia()) {
    try {
      if (item.kind === 'photo') {
        await keeperBot.sendPhoto(OWNER, item.buffer, { caption: item.caption });
      } else {
        await keeperBot.sendDocument(OWNER, item.buffer, { caption: item.caption }, { filename: item.filename, contentType: 'application/pdf' });
      }
    } catch (err) {
      console.error('[telegram] failed to send media:', err);
    }
  }
}

/**
 * Resolve an inbound message to plain text. Text messages pass through;
 * voice notes / audio get transcribed via Groq Whisper first.
 * Returns null if there's nothing actionable to send to the agent.
 */
async function extractText(msg: TelegramBot.Message): Promise<string | null> {
  if (msg.text && msg.text.trim()) return msg.text.trim();

  const media = msg.voice ?? msg.audio;
  if (media) {
    if (!transcriptionEnabled()) {
      await sendToOwner(
        "i can't listen to voice notes yet — drop a GROQ_API_KEY in my config and i'll have ears. for now, text me?"
      );
      return null;
    }
    try {
      await keeperBot.sendChatAction(OWNER, 'typing');
      const fileUrl = await keeperBot.getFileLink(media.file_id);
      const transcript = await transcribeFromUrl(fileUrl);
      console.log(`[telegram] transcribed voice note (${transcript.length} chars).`);
      return transcript;
    } catch (err) {
      console.error('[telegram] transcription failed:', err);
      await sendToOwner("i couldn't make out that voice note — mind sending it again or texting it?");
      return null;
    }
  }

  return null; // stickers, photos, etc. — nothing to act on
}

/** Download a Telegram document and return its text contents. */
async function downloadText(bot: TelegramBot, fileId: string): Promise<string> {
  const fileUrl = await bot.getFileLink(fileId);
  const res = await fetch(fileUrl);
  return res.text();
}

/** Download a Telegram file and return its raw bytes (for images, etc.). */
async function downloadBuffer(bot: TelegramBot, fileId: string): Promise<Buffer> {
  const fileUrl = await bot.getFileLink(fileId);
  const res = await fetch(fileUrl);
  return Buffer.from(await res.arrayBuffer());
}

/** Claude's vision accepts these image types only. */
type VisionMediaType = 'image/jpeg' | 'image/png' | 'image/gif' | 'image/webp';
const MAX_IMAGE_BYTES = 5 * 1024 * 1024; // Anthropic per-image base64 limit.
// PDFs up to this size go to the model natively (inline); larger fall back to
// server-side text extraction. Keeps the request under provider inline limits.
const NATIVE_PDF_MAX_BYTES = 12 * 1024 * 1024;

/** Map a Telegram mime/filename to a vision media type, or null if unsupported. */
function visionMediaType(mime: string | undefined, name: string): VisionMediaType | null {
  const m = (mime ?? '').toLowerCase();
  if (m === 'image/jpeg' || m === 'image/jpg') return 'image/jpeg';
  if (m === 'image/png') return 'image/png';
  if (m === 'image/gif') return 'image/gif';
  if (m === 'image/webp') return 'image/webp';
  const ext = name.toLowerCase().match(/\.\w+$/)?.[0] ?? '';
  if (ext === '.jpg' || ext === '.jpeg') return 'image/jpeg';
  if (ext === '.png') return 'image/png';
  if (ext === '.gif') return 'image/gif';
  if (ext === '.webp') return 'image/webp';
  return null;
}

/** Send an image to the agent for analysis and relay its reply. */
async function handleImage(
  fileId: string,
  mediaType: VisionMediaType,
  caption: string | undefined
): Promise<void> {
  const buf = await downloadBuffer(keeperBot, fileId);
  if (buf.length > MAX_IMAGE_BYTES) {
    await sendToOwner("that image is a bit too big for me to look at — can you send a smaller version?");
    return;
  }
  const result = await withTyping(() =>
    runAgent({
      kind: 'inbound',
      text: caption?.trim() ?? '',
      images: [{ mediaType, base64: buf.toString('base64') }],
    })
  );
  if (result.message) await sendToOwner(result.message);
  await flushMediaToOwner();
}

/** Instant ops snapshot for Philip — answered locally, no agent run, no tokens. */
async function sendStatus(): Promise<void> {
  const up = Math.floor((Date.now() - BOOTED_AT) / 1000);
  const uptime = `${Math.floor(up / 86400)}d ${Math.floor((up % 86400) / 3600)}h ${Math.floor((up % 3600) / 60)}m`;
  const [pending, lastJournal, dayTurns, monthTurns, activeGoals, latest, dig] = await Promise.all([
    touchpoints.pending().catch(() => []),
    journal.recent(1).catch(() => []),
    observations.series('sys.turn', localMidnightUtc().toISOString()).catch(() => []),
    observations.series('sys.turn', monthStartUtc().toISOString()).catch(() => []),
    goals.list(true).catch(() => []),
    observations.latestPerMetric().catch(() => []),
    digests.get('rolling').catch(() => null),
  ]);
  const usd = (rows: { value: number | null }[]) =>
    rows.reduce((a, r) => a + Number(r.value ?? 0), 0);
  const next = pending[0];
  const metricCount = latest.filter((o) => !o.metric.startsWith('sys.')).length;
  const on = (b: boolean) => (b ? 'on' : 'off');
  await keeperBot.sendMessage(
    OWNER,
    `keeper status\n` +
      `up: ${uptime}\n` +
      `model: ${config.model}\n` +
      `spend: today ~$${usd(dayTurns).toFixed(2)} (${dayTurns.length} runs) · month ~$${usd(monthTurns).toFixed(2)}\n` +
      `tracking: ${metricCount} metrics · ${activeGoals.length} goals\n` +
      `window: ${dig?.covered_until ? `anchored at ${dig.covered_until.slice(0, 16).replace('T', ' ')} UTC` : 'not anchored yet'}\n` +
      `next reach-out: ${next ? `${next.fire_at}${next.recurrence ? ' ↻' : ''} — ${next.reason.slice(0, 80)}` : 'none pending'}\n` +
      `last journal: ${lastJournal[0]?.day ?? 'never'} (reflection ${config.reflectionHour}:00)\n` +
      `integrations: deploy ${on(githubEnabled())} | google ${on(googleEnabled())} | images ${on(imageGenEnabled())} | voice ${on(transcriptionEnabled())} | web on`
  );
}

/** The KEEPER bot — Philip only, full agent. */
function startKeeperBot(): void {
  keeperBot.on('message', async (msg) => {
    const chatId = String(msg.chat.id);
    // Single-user agent: ignore anyone who isn't the owner.
    if (chatId !== OWNER) {
      console.warn(`[telegram] ignoring message from non-owner chat ${chatId}`);
      return;
    }

    const text = await extractText(msg);
    if (!text) return;

    if (text.toLowerCase() === '/status') {
      try {
        await sendStatus();
      } catch (err) {
        console.error('[telegram] status failed:', err);
      }
      return;
    }

    try {
      const result = await withTyping(() => runAgent({ kind: 'inbound', text }));
      if (result.message) await sendToOwner(result.message);
      await flushMediaToOwner();
    } catch (err) {
      console.error('[telegram] runAgent failed:', err);
      await sendToOwner('(something glitched on my end — try me again in a sec)');
    }
  });

  // Photos (compressed images Telegram sends as msg.photo). Telegram always
  // re-encodes these as JPEG and offers several sizes — grab the largest.
  keeperBot.on('photo', async (msg) => {
    const chatId = String(msg.chat.id);
    if (chatId !== OWNER) return;
    const sizes = msg.photo;
    if (!sizes?.length) return;
    const largest = sizes[sizes.length - 1];
    if (!largest) return;
    try {
      await handleImage(largest.file_id, 'image/jpeg', msg.caption);
    } catch (err) {
      console.error('[telegram] photo handler failed:', err);
      await sendToOwner(`(couldn't process that image — ${(err as Error).message})`);
    }
  });

  // Document uploads: .html → deploy; .pdf → extract; image files → vision.
  keeperBot.on('document', async (msg) => {
    const chatId = String(msg.chat.id);
    if (chatId !== OWNER) return;

    const doc = msg.document;
    if (!doc) return;
    const name = doc.file_name ?? '';
    const ext = name.toLowerCase().match(/\.\w+$/)?.[0] ?? '';

    if (ext === '.html') {
      if (!githubEnabled()) {
        await sendToOwner("i can't deploy sites yet — i need GITHUB_TOKEN and GITHUB_USERNAME in my config.");
        return;
      }
      try {
        const html = await downloadText(keeperBot, doc.file_id);
        setPendingHtml({
          filename: name,
          contentBase64: Buffer.from(html).toString('base64'),
          sizeBytes: html.length,
        });
        const result = await withTyping(() =>
          runAgent({
            kind: 'inbound',
            text: `I just sent you an HTML file named "${name}" (${(html.length / 1e6).toFixed(2)} MB). Please deploy it to GitHub Pages and give me the live link.`,
          })
        );
        if (result.message) await sendToOwner(result.message);
        await flushMediaToOwner();
      } catch (err) {
        console.error('[telegram] html deploy failed:', err);
        await sendToOwner(`(couldn't deploy that file — ${(err as Error).message})`);
      }
      return;
    }

    if (ext === '.pdf') {
      try {
        const buf = await downloadBuffer(keeperBot, doc.file_id);
        const caption = msg.caption?.trim();
        if (buf.length <= NATIVE_PDF_MAX_BYTES) {
          // Native PDF: the model reads layout/tables directly — far better than
          // text extraction for bank statements (which jumble into columns).
          const result = await withTyping(() =>
            runAgent({
              kind: 'inbound',
              text: caption || `I sent you a PDF named "${name}". Read it and tell me what matters.`,
              pdfs: [{ base64: buf.toString('base64'), filename: name }],
            })
          );
          if (result.message) await sendToOwner(result.message);
          await flushMediaToOwner();
        } else {
          // Too large to inline — fall back to extracted text.
          const pdf = await extractPdfTextFromBuffer(buf);
          const truncNote = pdf.truncated
            ? `\n\n(note: pdf was long — only the first ~24k characters are included above)`
            : '';
          const result = await withTyping(() =>
            runAgent({
              kind: 'inbound',
              text:
                `I sent you a PDF named "${name}" (${pdf.pages} page${pdf.pages === 1 ? '' : 's'}). Here's its text content:\n\n` +
                pdf.text +
                truncNote,
            })
          );
          if (result.message) await sendToOwner(result.message);
          await flushMediaToOwner();
        }
      } catch (err) {
        console.error('[telegram] pdf handling failed:', err);
        await sendToOwner(`(couldn't read that PDF — ${(err as Error).message})`);
      }
      return;
    }

    // Plain-text files (.csv bank exports, .txt, .md) → straight into the turn.
    if (ext === '.csv' || ext === '.txt' || ext === '.md') {
      try {
        let text = await downloadText(keeperBot, doc.file_id);
        const truncated = text.length > 24_000;
        if (truncated) text = text.slice(0, 24_000);
        const result = await withTyping(() =>
          runAgent({
            kind: 'inbound',
            text:
              `I sent you a file named "${name}"${msg.caption ? ` with the note: "${msg.caption}"` : ''}. Its contents:\n\n` +
              text +
              (truncated ? '\n\n(note: file was long — truncated at ~24k characters)' : ''),
          })
        );
        if (result.message) await sendToOwner(result.message);
        await flushMediaToOwner();
      } catch (err) {
        console.error('[telegram] text file failed:', err);
        await sendToOwner(`(couldn't read that file — ${(err as Error).message})`);
      }
      return;
    }

    // Image files (sent uncompressed as a document) → Claude vision.
    const mediaType = visionMediaType(doc.mime_type, name);
    if (mediaType) {
      try {
        await handleImage(doc.file_id, mediaType, msg.caption);
      } catch (err) {
        console.error('[telegram] image document failed:', err);
        await sendToOwner(`(couldn't process that image — ${(err as Error).message})`);
      }
      return;
    }

    // Any other file type — nothing to act on silently.
  });

  keeperBot.on('polling_error', (err) => {
    console.error('[telegram] polling error:', err.message);
    if ((err as NodeJS.ErrnoException).code === 'EFATAL') {
      console.error('[telegram] fatal network error — restarting polling in 20s...');
      keeperBot.stopPolling()
        .then(() => new Promise<void>((r) => setTimeout(r, 20_000)))
        .then(() => keeperBot.startPolling())
        .catch((e) => { console.error('[telegram] polling restart failed, exiting:', e); process.exit(1); });
    }
  });
  console.log('[telegram] keeper bot listening (long-polling).');
}

/**
 * A GUEST deploy-only bot. No agent, no memory — send an .html file, get back a
 * GitHub Pages link on the guest's own account. Optionally locked to one chat.
 */
function startGuestBot(g: GuestBot): void {
  const bot = new TelegramBot(g.telegramBotToken, { polling: true });
  const enabled = githubCredsValid(g.github);
  const allowed = (chatId: string) => !g.chatId || chatId === g.chatId;
  const tag = `telegram:${g.name}`;

  bot.on('document', async (msg) => {
    const chatId = String(msg.chat.id);
    if (!allowed(chatId)) {
      console.warn(`[${tag}] ignoring document from chat ${chatId}`);
      return;
    }

    const doc = msg.document;
    if (!doc) return;
    const name = doc.file_name ?? '';
    if (!name.toLowerCase().endsWith('.html')) {
      await bot.sendMessage(chatId, "send me an .html file and i'll publish it to your github pages.");
      return;
    }
    if (!enabled) {
      await bot.sendMessage(chatId, "this bot isn't set up to deploy yet — its github access is missing.");
      return;
    }

    try {
      await bot.sendChatAction(chatId, 'typing');
      const html = await downloadText(bot, doc.file_id);
      const res = await deployHtml(g.github, {
        filename: name,
        contentBase64: Buffer.from(html).toString('base64'),
        sizeBytes: html.length,
      });
      if (res.ok) {
        await bot.sendMessage(chatId, `done ✅ your site is live in ~30–60s:\n${res.url}`);
      } else {
        await bot.sendMessage(chatId, `couldn't deploy that — ${res.error}`);
      }
    } catch (err) {
      console.error(`[${tag}] document handler failed:`, err);
      await bot.sendMessage(chatId, `couldn't deploy that — ${(err as Error).message}`);
    }
  });

  bot.on('message', async (msg) => {
    if (msg.document) return; // handled above
    const chatId = String(msg.chat.id);
    if (!allowed(chatId)) return;
    await bot.sendMessage(
      chatId,
      `hey — send me an .html file and i'll publish it to your github pages and send you the link. that's all i do here.`
    );
  });

  bot.on('polling_error', (err) => {
    console.error(`[${tag}] polling error:`, err.message);
    if ((err as NodeJS.ErrnoException).code === 'EFATAL') {
      console.error(`[${tag}] fatal network error — restarting polling in 20s...`);
      bot.stopPolling()
        .then(() => new Promise<void>((r) => setTimeout(r, 20_000)))
        .then(() => bot.startPolling())
        .catch((e) => { console.error(`[${tag}] polling restart failed, exiting:`, e); process.exit(1); });
    }
  });
  console.log(
    `[telegram] guest deploy bot "${g.name}" listening${g.chatId ? ` (locked to chat ${g.chatId})` : ''}` +
      `${enabled ? '' : ' — WARNING: github creds missing, deploys disabled'}.`
  );
}

export function startTelegram(): void {
  startKeeperBot();
  for (const g of config.guestBots) startGuestBot(g);
  if (config.guestBots.length > 0) {
    console.log(`[telegram] ${config.guestBots.length} guest bot(s) started.`);
  }
}
