import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { readFileSync, readdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, extname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { config } from '../config.js';
import { runAgent, type InboundImage, type InboundPdf } from '../agent/orchestrator.js';
import { localMidnightUtc } from '../agent/recurrence.js';
import {
  digests,
  domains,
  facts,
  goals,
  observations,
  touchpoints,
  interactions,
  journal,
} from '../db/repositories.js';
import { drainMedia } from '../generate/queue.js';
import { bus, type KeeperEvent } from './bus.js';
import {
  attachPushToBus,
  initPush,
  publicKey as pushPublicKey,
  removeSubscription,
  saveSubscription,
  sendPush,
} from './push.js';

/**
 * The web surface: one tiny HTTP server in the same process as the bot.
 *  GET  /            the UI shell
 *  GET  /app.css /app.js /sw.js /manifest.webmanifest /icons/* /fonts/*
 *                    static assets — public, see the note on auth below
 *  GET  /events      SSE stream — live turn/step/message/card/media events
 *  POST /send        send a message to the agent from the browser
 *  GET  /api/snapshot  the keeper's mind: sectors, facts, plans, journal, history
 *  GET  /api/push/key           the VAPID public key a browser needs to subscribe
 *  POST /api/push/subscribe     register this device for notifications
 *  POST /api/push/unsubscribe   drop it again
 *  POST /api/push/test          prove the whole chain works, end to end
 *
 * Auth: a single shared token (KEEPER_WEB_TOKEN). The browser asks once and
 * keeps it in localStorage. EventSource can't set headers, so /events accepts
 * the token as a query param — fine for a single-user app over HTTPS.
 *
 * Static assets are deliberately unauthenticated: the browser fetches the
 * manifest, registers the service worker and loads icons *before* the user has
 * entered a token, and iOS requests startup images with no credentials at all.
 * None of them carry data — every read of the keeper's actual memory stays
 * behind the token.
 */

const WEB_DIR = fileURLToPath(new URL('./', import.meta.url));

const sseClients = new Set<ServerResponse>();

// ── static assets ───────────────────────────────────────────────────────────

const MIME: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.webmanifest': 'application/manifest+json; charset=utf-8',
  '.png': 'image/png',
  '.woff2': 'font/woff2',
};

/** Long enough that a returning user never re-downloads; short enough that a
 *  regenerated icon set still lands within a week. */
const IMMUTABLE = 'public, max-age=604800';
/** Changes on every deploy, so it must be revalidated — the ETag makes that cheap. */
const REVALIDATE = 'no-cache';

interface Asset {
  body: Buffer;
  type: string;
  cache: string;
  etag: string;
}

const assets = new Map<string, Asset>();

function asset(body: Buffer, file: string, cache: string): Asset {
  return {
    body,
    type: MIME[extname(file)] ?? 'application/octet-stream',
    cache,
    etag: `"${createHash('sha256').update(body).digest('base64url').slice(0, 20)}"`,
  };
}

/**
 * Loads the shell into memory and stamps the service worker's version.
 *
 * The stamp is the point: a browser only re-installs a service worker when the
 * worker *script's own bytes* change. Hashing the shell into it means editing
 * app.css is enough to push every installed client onto the new build.
 */
function loadStatic(): void {
  const read = (f: string) => readFileSync(join(WEB_DIR, f));
  const ui = read('ui.html');
  const css = read('app.css');
  const js = read('app.js');

  const version = createHash('sha256')
    .update(ui).update(css).update(js)
    .digest('hex')
    .slice(0, 12);
  const sw = Buffer.from(read('sw.js').toString('utf-8').replace('__VERSION__', version), 'utf-8');

  assets.set('/app.css', asset(css, 'app.css', REVALIDATE));
  assets.set('/app.js', asset(js, 'app.js', REVALIDATE));
  assets.set('/sw.js', asset(sw, 'sw.js', REVALIDATE));
  assets.set('/manifest.webmanifest', asset(read('manifest.webmanifest'), 'manifest.webmanifest', REVALIDATE));

  // Generated by `npm run icons`. Read the directory rather than trusting the
  // request path — this is the whole traversal defence.
  for (const dir of ['icons', 'fonts']) {
    let files: string[] = [];
    try {
      files = readdirSync(join(WEB_DIR, dir));
    } catch {
      console.warn(`[web] no ${dir}/ directory — run \`npm run icons\``);
      continue;
    }
    for (const f of files) {
      if (!MIME[extname(f)]) continue;
      assets.set(`/${dir}/${f}`, asset(read(join(dir, f)), f, IMMUTABLE));
    }
  }

  // ui.html last so it can be looked up the same way, but it never caches.
  assets.set('/', asset(ui, 'ui.html', 'no-store, must-revalidate'));

  const bytes = [...assets.values()].reduce((a, x) => a + x.body.length, 0);
  console.log(`[web] ${assets.size} static assets (${(bytes / 1024 / 1024).toFixed(2)} MB), build ${version}`);
}

function sendAsset(req: IncomingMessage, res: ServerResponse, a: Asset): void {
  if (req.headers['if-none-match'] === a.etag) {
    res.writeHead(304, { ETag: a.etag, 'Cache-Control': a.cache });
    res.end();
    return;
  }
  res.writeHead(200, {
    'Content-Type': a.type,
    'Content-Length': a.body.length,
    'Cache-Control': a.cache,
    ETag: a.etag,
  });
  res.end(a.body);
}

function authed(req: IncomingMessage): boolean {
  if (!config.webToken) return true;
  const url = new URL(req.url ?? '/', 'http://x');
  const bearer = (req.headers.authorization ?? '').replace(/^Bearer\s+/i, '').trim();
  const token = bearer || url.searchParams.get('t') || '';
  return token.length > 0 && token === config.webToken;
}

function json(res: ServerResponse, status: number, body: unknown): void {
  const payload = JSON.stringify(body);
  res.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8' });
  res.end(payload);
}

function broadcast(event: KeeperEvent): void {
  const frame = `data: ${JSON.stringify(event)}\n\n`;
  for (const client of sseClients) {
    try {
      client.write(frame);
    } catch {
      sseClients.delete(client);
    }
  }
}

async function readBody(req: IncomingMessage, maxBytes = 64 * 1024): Promise<string> {
  const chunks: Buffer[] = [];
  let size = 0;
  for await (const chunk of req) {
    size += (chunk as Buffer).length;
    if (size > maxBytes) throw new Error('body too large');
    chunks.push(chunk as Buffer);
  }
  return Buffer.concat(chunks).toString('utf-8');
}

/** Allowed image types map (mirrors the model's vision support). */
const IMAGE_TYPES: Record<string, InboundImage['mediaType']> = {
  'image/jpeg': 'image/jpeg',
  'image/jpg': 'image/jpeg',
  'image/png': 'image/png',
  'image/gif': 'image/gif',
  'image/webp': 'image/webp',
};

interface UploadFile {
  name?: string;
  mime?: string;
  data?: string; // base64, no data-URL prefix
}

async function handleSend(req: IncomingMessage, res: ServerResponse): Promise<void> {
  let text: string;
  let files: UploadFile[];
  try {
    // Files (images/PDFs) ride in as base64 — allow a generous body.
    const body = JSON.parse(await readBody(req, 20 * 1024 * 1024)) as { text?: unknown; files?: unknown };
    text = String(body.text ?? '').trim();
    files = Array.isArray(body.files) ? (body.files as UploadFile[]) : [];
  } catch {
    json(res, 400, { ok: false, error: 'bad request body' });
    return;
  }
  if (!text && files.length === 0) {
    json(res, 400, { ok: false, error: 'empty message' });
    return;
  }

  // Split attachments into vision images and native PDFs.
  const images: InboundImage[] = [];
  const pdfs: InboundPdf[] = [];
  for (const f of files) {
    const data = typeof f.data === 'string' ? f.data : '';
    if (!data) continue;
    const mime = (f.mime ?? '').toLowerCase();
    const ext = (f.name ?? '').toLowerCase().match(/\.\w+$/)?.[0] ?? '';
    if (mime === 'application/pdf' || ext === '.pdf') {
      pdfs.push({ base64: data, filename: f.name });
    } else {
      const mediaType = IMAGE_TYPES[mime] ?? IMAGE_TYPES[`image/${ext.slice(1)}`];
      if (mediaType) images.push({ mediaType, base64: data });
    }
  }

  try {
    await runAgent({
      kind: 'inbound',
      text,
      surface: 'web',
      images: images.length ? images : undefined,
      pdfs: pdfs.length ? pdfs : undefined,
    });
    // Media generated this turn (images/PDFs) goes to the screen he's on.
    for (const item of drainMedia()) {
      const mime = item.kind === 'photo' ? 'image/png' : 'application/pdf';
      broadcast({
        type: 'media',
        kind: item.kind,
        dataUrl: `data:${mime};base64,${item.buffer.toString('base64')}`,
        filename: item.kind === 'document' ? item.filename : undefined,
      });
    }
    json(res, 200, { ok: true });
  } catch (err) {
    console.error('[web] runAgent failed:', err);
    broadcast({
      type: 'message',
      role: 'agent',
      content: '(something glitched on my end — try me again in a sec)',
      ts: new Date().toISOString(),
      source: 'inbound:web',
    });
    json(res, 500, { ok: false, error: 'agent error' });
  }
}

async function handleSnapshot(res: ServerResponse): Promise<void> {
  const [domainList, factList, pending, journalEntries, history, goalList, latestObs, dayTurns, dig] =
    await Promise.all([
      domains.list(),
      facts.all(),
      touchpoints.pending(),
      journal.recent(1),
      interactions.recent(40),
      goals.list(true),
      observations.latestPerMetric(),
      observations.series('sys.turn', localMidnightUtc().toISOString()).catch(() => []),
      digests.get('rolling').catch(() => null),
    ]);
  const slugById = new Map(domainList.map((d) => [d.id, d.slug]));
  json(res, 200, {
    domains: domainList.map((d) => ({
      slug: d.slug,
      name: d.name,
      priority: d.priority,
      description: d.description,
    })),
    facts: factList.map((f) => ({
      domain: f.domain_id ? slugById.get(f.domain_id) ?? '?' : 'general',
      key: f.key,
      value: f.value,
    })),
    goals: goalList.map((g) => ({
      title: g.title,
      metric: g.metric,
      target: g.target_value,
      unit: g.unit,
      deadline: g.deadline,
      why: g.why,
    })),
    metrics: latestObs
      .filter((o) => !o.metric.startsWith('sys.'))
      .map((o) => ({
        metric: o.metric,
        value: o.value ?? o.text_value,
        unit: o.unit,
        at: o.observed_at,
      })),
    spendTodayUsd: dayTurns.reduce((a, r) => a + Number(r.value ?? 0), 0),
    digest: dig ? { content: dig.content, coveredUntil: dig.covered_until } : null,
    touchpoints: pending.map((t) => ({ fireAt: t.fire_at, reason: t.reason, recurrence: t.recurrence })),
    journal: journalEntries[0] ?? null,
    history: history.map((h) => ({ role: h.role, content: h.content, ts: h.created_at })),
  });
}

/**
 * Registers this browser for notifications.
 *
 * The body is the browser's own PushSubscription.toJSON() — we never invent any
 * of it. `endpoint` is the URL of that device's mailbox at its push service;
 * the two keys are what the payload gets encrypted for.
 */
async function handleSubscribe(req: IncomingMessage, res: ServerResponse): Promise<void> {
  let sub: { endpoint?: unknown; keys?: { p256dh?: unknown; auth?: unknown } };
  try {
    sub = JSON.parse(await readBody(req)) as typeof sub;
  } catch {
    json(res, 400, { ok: false, error: 'bad request body' });
    return;
  }
  const endpoint = typeof sub.endpoint === 'string' ? sub.endpoint : '';
  const p256dh = typeof sub.keys?.p256dh === 'string' ? sub.keys.p256dh : '';
  const auth = typeof sub.keys?.auth === 'string' ? sub.keys.auth : '';
  if (!/^https:\/\//.test(endpoint) || !p256dh || !auth) {
    json(res, 400, { ok: false, error: 'not a usable push subscription' });
    return;
  }
  await saveSubscription({ endpoint, p256dh, auth, userAgent: req.headers['user-agent'] ?? null });
  json(res, 200, { ok: true });
}

function handleEvents(res: ServerResponse): void {
  res.writeHead(200, {
    'Content-Type': 'text/event-stream',
    'Cache-Control': 'no-cache, no-transform',
    Connection: 'keep-alive',
    'X-Accel-Buffering': 'no',
  });
  res.write(': connected\n\n');
  sseClients.add(res);
  res.on('close', () => sseClients.delete(res));
}

export function startWebServer(): void {
  if (!config.webToken) {
    console.log('[web] KEEPER_WEB_TOKEN not set — web UI running without auth.');
  }

  loadStatic();

  bus.subscribe(broadcast);

  // Notifications. initPush is async (it reads or mints the VAPID keypair) but
  // the bus hook is attached synchronously, so a reach-out that fires during
  // those first few hundred milliseconds is still seen — sendPush just no-ops
  // until the keys land.
  attachPushToBus();
  void initPush();

  // SSE connections die quietly on some proxies without traffic — heartbeat.
  setInterval(() => {
    for (const client of sseClients) {
      try {
        client.write(': ping\n\n');
      } catch {
        sseClients.delete(client);
      }
    }
  }, 25_000).unref();

  const server = createServer((req, res) => {
    const path = new URL(req.url ?? '/', 'http://x').pathname;

    // The shell and its assets: public, and never cached at the HTTP layer for
    // anything that changes on deploy. The service worker is what makes these
    // available offline.
    if (req.method === 'GET') {
      const hit = assets.get(path === '/index.html' ? '/' : path);
      if (hit) {
        sendAsset(req, res, hit);
        return;
      }
    }
    if (req.method === 'GET' && path === '/healthz') {
      json(res, 200, { ok: true });
      return;
    }

    // Everything below requires the token.
    if (!authed(req)) {
      json(res, 401, { ok: false, error: 'unauthorized' });
      return;
    }
    if (req.method === 'GET' && path === '/events') {
      handleEvents(res);
      return;
    }
    if (req.method === 'POST' && path === '/send') {
      void handleSend(req, res);
      return;
    }
    if (req.method === 'GET' && path === '/api/snapshot') {
      void handleSnapshot(res).catch((err) => {
        console.error('[web] snapshot failed:', err);
        json(res, 500, { ok: false });
      });
      return;
    }

    // ── notifications ──────────────────────────────────────────────────────
    if (req.method === 'GET' && path === '/api/push/key') {
      // null tells the UI the server can't do push at all, which is a different
      // story to tell the user than "you haven't turned it on".
      json(res, 200, { key: pushPublicKey() });
      return;
    }
    if (req.method === 'POST' && path === '/api/push/subscribe') {
      void handleSubscribe(req, res).catch((err) => {
        console.error('[web] push subscribe failed:', err);
        json(res, 500, { ok: false, error: 'could not save that subscription' });
      });
      return;
    }
    if (req.method === 'POST' && path === '/api/push/unsubscribe') {
      void (async () => {
        const { endpoint } = JSON.parse(await readBody(req)) as { endpoint?: string };
        if (endpoint) await removeSubscription(endpoint);
        json(res, 200, { ok: true });
      })().catch(() => json(res, 400, { ok: false, error: 'bad request body' }));
      return;
    }
    if (req.method === 'POST' && path === '/api/push/test') {
      void (async () => {
        const { sent, devices } = await sendPush({
          title: 'keeper',
          body: 'this is what it looks like when i reach out.',
          tag: 'keeper-test',
          url: '/',
          ts: new Date().toISOString(),
          force: true,
        });
        json(res, 200, { ok: sent > 0, sent, devices });
      })().catch((err) => {
        console.error('[web] push test failed:', err);
        json(res, 500, { ok: false, error: 'could not send it' });
      });
      return;
    }

    json(res, 404, { ok: false, error: 'not found' });
  });

  server.listen(config.port, () => {
    console.log(`[web] ui listening on :${config.port}`);
  });
}
